apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  tasks:
  - name: print-hello-world
    taskRef:
      apiVersion: tekton.dev/v1alpha1
      kind: Task
      name: print-hello-world-task
    params:
    - name: message
      value: "Hello, world!"
