# wf-helloworld.yaml

name: testworkflow
serviceAccount: "projects/cloud-aoss-dev/serviceAccounts/cloudbuildgen2@cloud-aoss-dev.iam.gserviceaccount.com"

pipeline:
  spec:
    tasks:
    - name: pipeline-task
      taskSpec:
        steps:
        - image: busybox
          script: echo "Hello World!"

options:
  executionEnvironment:
    workerPool: "projects/cloud-aoss-dev/locations/us-central1/workerPools/testPoolV2"
